name: CI

on: 
  push:
    branches:
      - main
    
  pull_request:
    branches: 
      - main  

jobs: 
  install-deps: 
    name: Install dependencies and Build
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - uses: ./.github/actions/setup

      - name: Build
        run: pnpm build

  lint: 
    name: Lint
    runs-on: ubuntu-latest
    needs: install-deps

    steps: 
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - uses: ./.github/actions/setup

      - name: Lint
        run: pnpm ci:lint

  test-unit: 
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: install-deps

    steps: 
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - uses: ./.github/actions/setup

      - name: Run Unit Tests
        run: pnpm test:unit