name: CI

on: 
  push:
    branches:
      - main
    paths-ignore: 
        - 'scripts/**'
        - '**.md' 
        - '.vscode'
        - '.husky'

  pull_request:
    branches: 
      - main  
  workflow_dispatch: 

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs: 
  install-deps: 
    name: Install dependencies and Build
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - uses: ./.github/actions/setup

      - name: Build
        run: pnpm run build

  lint: 
    name: Lint
    runs-on: ubuntu-latest
    needs: install-deps

    steps: 
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - uses: ./.github/actions/setup

      - name: Lint
        run: pnpm run ci:lint

  test-unit: 
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: install-deps

    steps: 
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - uses: ./.github/actions/setup

      - name: Run Unit Tests
        run: pnpm run test:unit