name: Release Canary

on: 
  workflow_dispatch: 

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions: 
  id-token: write

jobs:
  release-canary: 
    name: Publish Canary release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Add changeset
        run: cp ./.github/canary-changeset.md .changeset/

      - name: Update version
        run: pnpm ci:version:canary

      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: Setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER
      
      - name: Publish to npm
        run: | 
          pnpm ci:publish:canary
          rm .npmrc
          pnpm config delete store-dir $PNPM_CACHE_FOLDER

      
