name: Release Canary

on: 
  workflow_dispatch: 

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions: 
  id-token: write

jobs:
  release-canary: 
    name: Publish Canary release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Add changeset
        run: cp ./.github/canary-changeset.md .changeset/

      - name: Update version
        run: pnpm run ci:version:canary
      
      - name: Publish to npm
        run:  pnpm run ci:publish:canary

        env: 
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}