name: Release

on: 
  push: 
    branches: 
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions: 
  id-token: write
  contents: write
  pull-requests: write

jobs:
  prepare: 
    name: Prepare Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with: 
          version: pnpm ci:version
          title: 'chore: version packages'
          commit: 'chore: version packages'
          createGithubReleases: false
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish: 
    name: Publish 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Publish to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          pnpm config set npmAuthToken ${{ secrets.NPM_TOKEN }}
          pnpm ci:publish
          rm ".npmrc"
          pnpm config delete npmAuthToken