name: Release Canary

on: 
  workflow_dispatch: 

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions: 
  id-token: write

jobs:
  release-canary: 
    name: Publish Canary release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Add changeset
        run: cp ./.github/canary-changeset.md .changeset/

      - name: Update version
        run: pnpm ci:version:canary

      - name: Publish to NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          yarn config set npmAuthToken ${{ secrets.NPM_TOKEN }}
          yarn ci:publish
          rm ".npmrc"
          yarn config unset npmAuthToken